// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQj8Xt7VJr2KgSfFjNs2Hf8AUPdQk7-Ls',
    appId: '1:123456789012:web:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'hub4apps-mindfulliving',
    authDomain: 'hub4apps-mindfulliving.firebaseapp.com',
    storageBucket: 'hub4apps-mindfulliving.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0DcOR_S3WlTcXdgHf_ml47FK2KuCaAx0',
    appId: '1:456746876426:android:a98b9f966cff77c90e69f3',
    messagingSenderId: '456746876426',
    projectId: 'hub4apps-mindfulliving',
    databaseURL: 'https://hub4apps-mindfulliving-default-rtdb.firebaseio.com',
    storageBucket: 'hub4apps-mindfulliving.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFDUteVEkm16rEvDJveS790rGIqACmREI',
    appId: '1:456746876426:ios:3068be4a05ed981c0e69f3',
    messagingSenderId: '456746876426',
    projectId: 'hub4apps-mindfulliving',
    databaseURL: 'https://hub4apps-mindfulliving-default-rtdb.firebaseio.com',
    storageBucket: 'hub4apps-mindfulliving.firebasestorage.app',
    iosBundleId: 'com.hub4apps.mindfulLiving',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQj8Xt7VJr2KgSfFjNs2Hf8AUPdQk7-Ls',
    appId: '1:123456789012:macos:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'hub4apps-mindfulliving',
    authDomain: 'hub4apps-mindfulliving.firebaseapp.com',
    storageBucket: 'hub4apps-mindfulliving.appspot.com',
    iosBundleId: 'com.hub4apps.mindfulliving',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQj8Xt7VJr2KgSfFjNs2Hf8AUPdQk7-Ls',
    appId: '1:123456789012:windows:abc123def456',
    messagingSenderId: '123456789012',
    projectId: 'hub4apps-mindfulliving',
    authDomain: 'hub4apps-mindfulliving.firebaseapp.com',
    storageBucket: 'hub4apps-mindfulliving.appspot.com',
  );
}